// Code generated by protoc-gen-gogo.
// source: imsg.proto
// DO NOT EDIT!

/*
	Package imsg is a generated protocol buffer package.

	It is generated from these files:
		imsg.proto

	It has these top-level messages:
		Entity
		EnterSceneReq
		ExitSceneReq
		SwitchCellReq
		SwitchCellRep
		AuthReq
		AuthRep
		AddGhost
		SyncGhost
		RemoveGhost
*/
package imsg

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import msg "s9/msg"
import actor "github.com/AsynkronIT/protoactor-go/actor"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Entity struct {
	Data     *msg.PlayerData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	AgentPID *actor.PID      `protobuf:"bytes,2,opt,name=agentPID" json:"agentPID,omitempty"`
	CellPID  *actor.PID      `protobuf:"bytes,3,opt,name=cellPID" json:"cellPID,omitempty"`
	LastPos  *msg.Vector2    `protobuf:"bytes,4,opt,name=lastPos" json:"lastPos,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{0} }

func (m *Entity) GetData() *msg.PlayerData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Entity) GetAgentPID() *actor.PID {
	if m != nil {
		return m.AgentPID
	}
	return nil
}

func (m *Entity) GetCellPID() *actor.PID {
	if m != nil {
		return m.CellPID
	}
	return nil
}

func (m *Entity) GetLastPos() *msg.Vector2 {
	if m != nil {
		return m.LastPos
	}
	return nil
}

type EnterSceneReq struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *EnterSceneReq) Reset()                    { *m = EnterSceneReq{} }
func (*EnterSceneReq) ProtoMessage()               {}
func (*EnterSceneReq) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{1} }

func (m *EnterSceneReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ExitSceneReq struct {
	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Entity *Entity `protobuf:"bytes,2,opt,name=entity" json:"entity,omitempty"`
}

func (m *ExitSceneReq) Reset()                    { *m = ExitSceneReq{} }
func (*ExitSceneReq) ProtoMessage()               {}
func (*ExitSceneReq) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{2} }

func (m *ExitSceneReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExitSceneReq) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SwitchCellReq struct {
	Entity *Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *SwitchCellReq) Reset()                    { *m = SwitchCellReq{} }
func (*SwitchCellReq) ProtoMessage()               {}
func (*SwitchCellReq) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{3} }

func (m *SwitchCellReq) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SwitchCellRep struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *SwitchCellRep) Reset()                    { *m = SwitchCellRep{} }
func (*SwitchCellRep) ProtoMessage()               {}
func (*SwitchCellRep) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{4} }

func (m *SwitchCellRep) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AuthReq struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *AuthReq) Reset()                    { *m = AuthReq{} }
func (*AuthReq) ProtoMessage()               {}
func (*AuthReq) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{5} }

func (m *AuthReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type AuthRep struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *AuthRep) Reset()                    { *m = AuthRep{} }
func (*AuthRep) ProtoMessage()               {}
func (*AuthRep) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{6} }

func (m *AuthRep) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AddGhost struct {
	Entity *Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *AddGhost) Reset()                    { *m = AddGhost{} }
func (*AddGhost) ProtoMessage()               {}
func (*AddGhost) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{7} }

func (m *AddGhost) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type SyncGhost struct {
	Entity *Entity `protobuf:"bytes,1,opt,name=entity" json:"entity,omitempty"`
}

func (m *SyncGhost) Reset()                    { *m = SyncGhost{} }
func (*SyncGhost) ProtoMessage()               {}
func (*SyncGhost) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{8} }

func (m *SyncGhost) GetEntity() *Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

type RemoveGhost struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *RemoveGhost) Reset()                    { *m = RemoveGhost{} }
func (*RemoveGhost) ProtoMessage()               {}
func (*RemoveGhost) Descriptor() ([]byte, []int) { return fileDescriptorImsg, []int{9} }

func (m *RemoveGhost) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Entity)(nil), "imsg.Entity")
	proto.RegisterType((*EnterSceneReq)(nil), "imsg.EnterSceneReq")
	proto.RegisterType((*ExitSceneReq)(nil), "imsg.ExitSceneReq")
	proto.RegisterType((*SwitchCellReq)(nil), "imsg.SwitchCellReq")
	proto.RegisterType((*SwitchCellRep)(nil), "imsg.SwitchCellRep")
	proto.RegisterType((*AuthReq)(nil), "imsg.AuthReq")
	proto.RegisterType((*AuthRep)(nil), "imsg.AuthRep")
	proto.RegisterType((*AddGhost)(nil), "imsg.AddGhost")
	proto.RegisterType((*SyncGhost)(nil), "imsg.SyncGhost")
	proto.RegisterType((*RemoveGhost)(nil), "imsg.RemoveGhost")
}
func (this *Entity) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Entity)
	if !ok {
		that2, ok := that.(Entity)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Data.Equal(that1.Data) {
		return false
	}
	if !this.AgentPID.Equal(that1.AgentPID) {
		return false
	}
	if !this.CellPID.Equal(that1.CellPID) {
		return false
	}
	if !this.LastPos.Equal(that1.LastPos) {
		return false
	}
	return true
}
func (this *EnterSceneReq) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*EnterSceneReq)
	if !ok {
		that2, ok := that.(EnterSceneReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	return true
}
func (this *ExitSceneReq) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*ExitSceneReq)
	if !ok {
		that2, ok := that.(ExitSceneReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if !this.Entity.Equal(that1.Entity) {
		return false
	}
	return true
}
func (this *SwitchCellReq) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SwitchCellReq)
	if !ok {
		that2, ok := that.(SwitchCellReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Entity.Equal(that1.Entity) {
		return false
	}
	return true
}
func (this *SwitchCellRep) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SwitchCellRep)
	if !ok {
		that2, ok := that.(SwitchCellRep)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	return true
}
func (this *AuthReq) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*AuthReq)
	if !ok {
		that2, ok := that.(AuthReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Account != that1.Account {
		return false
	}
	return true
}
func (this *AuthRep) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*AuthRep)
	if !ok {
		that2, ok := that.(AuthRep)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	return true
}
func (this *AddGhost) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*AddGhost)
	if !ok {
		that2, ok := that.(AddGhost)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Entity.Equal(that1.Entity) {
		return false
	}
	return true
}
func (this *SyncGhost) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SyncGhost)
	if !ok {
		that2, ok := that.(SyncGhost)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Entity.Equal(that1.Entity) {
		return false
	}
	return true
}
func (this *RemoveGhost) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*RemoveGhost)
	if !ok {
		that2, ok := that.(RemoveGhost)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	return true
}
func (this *Entity) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&imsg.Entity{")
	if this.Data != nil {
		s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	}
	if this.AgentPID != nil {
		s = append(s, "AgentPID: "+fmt.Sprintf("%#v", this.AgentPID)+",\n")
	}
	if this.CellPID != nil {
		s = append(s, "CellPID: "+fmt.Sprintf("%#v", this.CellPID)+",\n")
	}
	if this.LastPos != nil {
		s = append(s, "LastPos: "+fmt.Sprintf("%#v", this.LastPos)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *EnterSceneReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&imsg.EnterSceneReq{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ExitSceneReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&imsg.ExitSceneReq{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	if this.Entity != nil {
		s = append(s, "Entity: "+fmt.Sprintf("%#v", this.Entity)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SwitchCellReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&imsg.SwitchCellReq{")
	if this.Entity != nil {
		s = append(s, "Entity: "+fmt.Sprintf("%#v", this.Entity)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SwitchCellRep) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&imsg.SwitchCellRep{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *AuthReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&imsg.AuthReq{")
	s = append(s, "Account: "+fmt.Sprintf("%#v", this.Account)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *AuthRep) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&imsg.AuthRep{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *AddGhost) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&imsg.AddGhost{")
	if this.Entity != nil {
		s = append(s, "Entity: "+fmt.Sprintf("%#v", this.Entity)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SyncGhost) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&imsg.SyncGhost{")
	if this.Entity != nil {
		s = append(s, "Entity: "+fmt.Sprintf("%#v", this.Entity)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RemoveGhost) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&imsg.RemoveGhost{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringImsg(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Entity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Entity) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Data.Size()))
		n1, err := m.Data.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.AgentPID != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.AgentPID.Size()))
		n2, err := m.AgentPID.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.CellPID != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.CellPID.Size()))
		n3, err := m.CellPID.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.LastPos != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.LastPos.Size()))
		n4, err := m.LastPos.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}

func (m *EnterSceneReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EnterSceneReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *ExitSceneReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExitSceneReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Id))
	}
	if m.Entity != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Entity.Size()))
		n5, err := m.Entity.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}

func (m *SwitchCellReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwitchCellReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Entity != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Entity.Size()))
		n6, err := m.Entity.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}

func (m *SwitchCellRep) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwitchCellRep) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *AuthReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintImsg(dAtA, i, uint64(len(m.Account)))
		i += copy(dAtA[i:], m.Account)
	}
	return i, nil
}

func (m *AuthRep) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuthRep) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *AddGhost) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddGhost) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Entity != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Entity.Size()))
		n7, err := m.Entity.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}

func (m *SyncGhost) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncGhost) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Entity != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Entity.Size()))
		n8, err := m.Entity.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	return i, nil
}

func (m *RemoveGhost) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveGhost) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintImsg(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func encodeFixed64Imsg(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Imsg(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintImsg(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Entity) Size() (n int) {
	var l int
	_ = l
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovImsg(uint64(l))
	}
	if m.AgentPID != nil {
		l = m.AgentPID.Size()
		n += 1 + l + sovImsg(uint64(l))
	}
	if m.CellPID != nil {
		l = m.CellPID.Size()
		n += 1 + l + sovImsg(uint64(l))
	}
	if m.LastPos != nil {
		l = m.LastPos.Size()
		n += 1 + l + sovImsg(uint64(l))
	}
	return n
}

func (m *EnterSceneReq) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovImsg(uint64(m.Id))
	}
	return n
}

func (m *ExitSceneReq) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovImsg(uint64(m.Id))
	}
	if m.Entity != nil {
		l = m.Entity.Size()
		n += 1 + l + sovImsg(uint64(l))
	}
	return n
}

func (m *SwitchCellReq) Size() (n int) {
	var l int
	_ = l
	if m.Entity != nil {
		l = m.Entity.Size()
		n += 1 + l + sovImsg(uint64(l))
	}
	return n
}

func (m *SwitchCellRep) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovImsg(uint64(m.Id))
	}
	return n
}

func (m *AuthReq) Size() (n int) {
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovImsg(uint64(l))
	}
	return n
}

func (m *AuthRep) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovImsg(uint64(m.Id))
	}
	return n
}

func (m *AddGhost) Size() (n int) {
	var l int
	_ = l
	if m.Entity != nil {
		l = m.Entity.Size()
		n += 1 + l + sovImsg(uint64(l))
	}
	return n
}

func (m *SyncGhost) Size() (n int) {
	var l int
	_ = l
	if m.Entity != nil {
		l = m.Entity.Size()
		n += 1 + l + sovImsg(uint64(l))
	}
	return n
}

func (m *RemoveGhost) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovImsg(uint64(m.Id))
	}
	return n
}

func sovImsg(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozImsg(x uint64) (n int) {
	return sovImsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Entity) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Entity{`,
		`Data:` + strings.Replace(fmt.Sprintf("%v", this.Data), "PlayerData", "msg.PlayerData", 1) + `,`,
		`AgentPID:` + strings.Replace(fmt.Sprintf("%v", this.AgentPID), "PID", "actor.PID", 1) + `,`,
		`CellPID:` + strings.Replace(fmt.Sprintf("%v", this.CellPID), "PID", "actor.PID", 1) + `,`,
		`LastPos:` + strings.Replace(fmt.Sprintf("%v", this.LastPos), "Vector2", "msg.Vector2", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *EnterSceneReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&EnterSceneReq{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ExitSceneReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ExitSceneReq{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Entity:` + strings.Replace(fmt.Sprintf("%v", this.Entity), "Entity", "Entity", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SwitchCellReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SwitchCellReq{`,
		`Entity:` + strings.Replace(fmt.Sprintf("%v", this.Entity), "Entity", "Entity", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SwitchCellRep) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SwitchCellRep{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AuthReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AuthReq{`,
		`Account:` + fmt.Sprintf("%v", this.Account) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AuthRep) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AuthRep{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AddGhost) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AddGhost{`,
		`Entity:` + strings.Replace(fmt.Sprintf("%v", this.Entity), "Entity", "Entity", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SyncGhost) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SyncGhost{`,
		`Entity:` + strings.Replace(fmt.Sprintf("%v", this.Entity), "Entity", "Entity", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RemoveGhost) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RemoveGhost{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringImsg(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Entity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Entity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Entity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthImsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &msg.PlayerData{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentPID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthImsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AgentPID == nil {
				m.AgentPID = &actor.PID{}
			}
			if err := m.AgentPID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CellPID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthImsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CellPID == nil {
				m.CellPID = &actor.PID{}
			}
			if err := m.CellPID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthImsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastPos == nil {
				m.LastPos = &msg.Vector2{}
			}
			if err := m.LastPos.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EnterSceneReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EnterSceneReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EnterSceneReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExitSceneReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExitSceneReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExitSceneReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthImsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Entity == nil {
				m.Entity = &Entity{}
			}
			if err := m.Entity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SwitchCellReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwitchCellReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwitchCellReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthImsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Entity == nil {
				m.Entity = &Entity{}
			}
			if err := m.Entity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SwitchCellRep) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwitchCellRep: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwitchCellRep: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthImsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuthRep) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuthRep: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuthRep: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddGhost) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddGhost: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddGhost: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthImsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Entity == nil {
				m.Entity = &Entity{}
			}
			if err := m.Entity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SyncGhost) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncGhost: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncGhost: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthImsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Entity == nil {
				m.Entity = &Entity{}
			}
			if err := m.Entity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveGhost) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveGhost: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveGhost: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipImsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthImsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipImsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowImsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowImsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthImsg
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowImsg
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipImsg(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthImsg = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowImsg   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("imsg.proto", fileDescriptorImsg) }

var fileDescriptorImsg = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xb1, 0x8e, 0xd3, 0x40,
	0x14, 0x45, 0x3d, 0x21, 0xc4, 0xbb, 0x6f, 0xb3, 0x80, 0x5c, 0x99, 0x95, 0x98, 0x45, 0xde, 0x55,
	0x44, 0x01, 0x36, 0x04, 0x81, 0x44, 0x19, 0x70, 0x84, 0xd2, 0x59, 0x13, 0x44, 0x3f, 0x19, 0x8f,
	0x6c, 0x0b, 0x7b, 0x26, 0x78, 0x26, 0x80, 0x3b, 0x3e, 0x81, 0x7f, 0xa0, 0xe1, 0x53, 0x28, 0x53,
	0x52, 0x12, 0xd3, 0x50, 0xe6, 0x13, 0x90, 0xc7, 0x71, 0x10, 0x44, 0x20, 0xe8, 0x9e, 0xdf, 0xb9,
	0xf7, 0xfa, 0x3e, 0xcb, 0x00, 0x59, 0xa1, 0x12, 0x7f, 0x59, 0x4a, 0x2d, 0x9d, 0x7e, 0x33, 0x9f,
	0xdd, 0x50, 0x4f, 0x82, 0x42, 0x25, 0xc1, 0x7e, 0x7f, 0xf6, 0x38, 0xc9, 0x74, 0xba, 0x5a, 0xf8,
	0x4c, 0x16, 0xc1, 0x44, 0x55, 0xe2, 0x55, 0x29, 0xc5, 0xec, 0x45, 0x60, 0x20, 0x65, 0x5a, 0x96,
	0xf7, 0x12, 0x19, 0x98, 0xa1, 0xdd, 0xa9, 0xd6, 0xe7, 0x7d, 0x44, 0x30, 0x98, 0x0a, 0x9d, 0xe9,
	0xca, 0xb9, 0x80, 0x7e, 0x4c, 0x35, 0x75, 0xd1, 0x6d, 0x74, 0xe7, 0x64, 0x7c, 0xdd, 0x6f, 0xc2,
	0xa3, 0x9c, 0x56, 0xbc, 0x0c, 0xa9, 0xa6, 0xc4, 0x40, 0x67, 0x04, 0x47, 0x34, 0xe1, 0x42, 0x47,
	0xb3, 0xd0, 0xed, 0x19, 0x21, 0xf8, 0x26, 0xd6, 0x8f, 0x66, 0x21, 0xd9, 0x33, 0xe7, 0x12, 0x6c,
	0xc6, 0xf3, 0xbc, 0x91, 0x5d, 0x39, 0x90, 0x75, 0xc8, 0x19, 0x81, 0x9d, 0x53, 0xa5, 0x23, 0xa9,
	0xdc, 0xbe, 0x51, 0x0d, 0xcd, 0x5b, 0x5f, 0xf2, 0x46, 0x3a, 0x26, 0x1d, 0xf4, 0xce, 0xe1, 0x74,
	0x2a, 0x34, 0x2f, 0xe7, 0x8c, 0x0b, 0x4e, 0xf8, 0x6b, 0xe7, 0x1a, 0xf4, 0xb2, 0xd8, 0x34, 0xbd,
	0x4a, 0x7a, 0x59, 0xec, 0x85, 0x30, 0x9c, 0xbe, 0xcb, 0xf4, 0x9f, 0xb8, 0x73, 0x09, 0x03, 0x6e,
	0xae, 0xdc, 0x95, 0x1e, 0xfa, 0xe6, 0x9b, 0xb6, 0x97, 0x93, 0x1d, 0xf3, 0x1e, 0xc1, 0xe9, 0xfc,
	0x6d, 0xa6, 0x59, 0xfa, 0x8c, 0xe7, 0x79, 0x13, 0xf3, 0xd3, 0x86, 0xfe, 0x62, 0x3b, 0xff, 0xd5,
	0xb6, 0x3c, 0x68, 0x77, 0x01, 0xf6, 0x64, 0xa5, 0xd3, 0x26, 0xd1, 0x05, 0x9b, 0x32, 0x26, 0x57,
	0x42, 0x1b, 0x7e, 0x4c, 0xba, 0x47, 0xef, 0x66, 0x27, 0x3a, 0xf4, 0xdf, 0x87, 0xa3, 0x49, 0x1c,
	0x3f, 0x4f, 0xa5, 0xd2, 0xff, 0x58, 0xe9, 0x01, 0x1c, 0xcf, 0x2b, 0xc1, 0xfe, 0xc7, 0x72, 0x0b,
	0x4e, 0x08, 0x2f, 0xe4, 0x1b, 0xde, 0x9a, 0x7e, 0xeb, 0xf0, 0xf4, 0xee, 0x7a, 0x83, 0xad, 0x2f,
	0x1b, 0x6c, 0x6d, 0x37, 0x18, 0xbd, 0xaf, 0x31, 0xfa, 0x54, 0x63, 0xf4, 0xb9, 0xc6, 0x68, 0x5d,
	0x63, 0xf4, 0xb5, 0xc6, 0xe8, 0x7b, 0x8d, 0xad, 0x6d, 0x8d, 0xd1, 0x87, 0x6f, 0xd8, 0x5a, 0x0c,
	0xcc, 0xdf, 0xf5, 0xf0, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0x13, 0x5f, 0x9a, 0xbb, 0x02,
	0x00, 0x00,
}
